# Generated by Django 4.1.7 on 2023-03-08 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
